language: node_js

cache:
  directories:
    - node_modules

node_js:
  - '5.0'

script:
  - npm run build release

before_deploy:
  - ./scripts/before-deploy.sh

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket:
      secure: cJBWCJ9zu4VmAVUL6RbXnMgFfjPv2N98ro/gX8SUsce4dzypS0aihZ4p4hV40/kl995t/4C8FE0eSemIGD5idMKvvBBnDfwozlAYn1bYdqDGo6rZ3oaoCC56gNPC6++JUUZmmQd17dmddzmhghIXIYCtYrZake4IVo3QPaCFJfE9wcKul8xjOVG/Lfm1Gyp/D7cF4/WS8Y9yvC/ATE0Dp56UtKY3F30A+UH1datDgM3buxBU8A83JWPZCleP9Qksii5SMXOm4aYdydL+i9ktjIYPu6mSP09TEGCbca4xUKKQ2rM9k8VXLLTDFonh73NiJUejBgCplU6wwnYon0Wn4y4JlWzgPbcTf+j6KtSG2az/yJG+YlMLaTXWggrnyz5mjmW9TXEs/l+S7dCTndnIXOIur6z9xBLiBj6I1DXExZVweuQ8ZNX+IeonFW0yvq8LCjTN6WMme9ELhHeUe1tKlamsrERiDeAD/QL27/9KyliG3+qRc/5b9x+lGa91+5cAfV60bdYxdwCChkUpPJiHdfACjt2pO0pcH2yHiR/Jk3x8cENOUP09UbhPb7s3kwjyZWmmDmeTB11f244kurxDL6QDaPRxpQeka5im/YOPiQHUPH2lb0sg58TboT5YhYnC5+ranvoLsn4zvWkwix/a3H7xBG92idEl57A0Z3HeXGU=
    skip_cleanup: true
    acl: public_read
    local_dir: build
    on:
      repo: SkygearIO/skygear-doc
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: docs.skygear.io
    skip_cleanup: true
    acl: public_read
    local_dir: build
    on:
      repo: SkygearIO/skygear-doc
      branch: $PRODUCTION_BRANCH

after_deploy:
  - ./scripts/after-deploy.sh

notifications:
  slack:
    secure: "Sd0JDpUu/kLJ6Gm5zUZ/aNbaGmqeU7cq0e2mH11exxBgVLR0AQmnm2N86pcP3tK8OPnsaumtqlQuKzcHfXjngTEvJ8e4sqaEtAvGRM0dU2e668CM6GOICxzequkki067MP4sa6EDuFsAw41WUl6oHJDZub1Op3XYHVEAlhHG6vUFTyAgEcJeValfIufPNO+m8vl/S7rOwi/ZrgY4mJdBaSRiSADxrBFySZj5EN4+PHHqLwHj4oCvcFUPeCEXae19rlVadz9yp0GITepT9gisacggQ7KzKgQb/q4b6srliMzmqZ3lb/mTT3bwG62aHrvOD5CBT0RSsxOntOhTNHK3YkYQS1BvQPckbFDEsMwdh7ZxlcithDARk3oG7cvmTEAgOIU1HQJt285tZskPkt10Fzg5WmM0DrzBzHc/47aJljauGcJFEcyipaLkUTL3GwcIjgLKhYai/STEMach8gP6rjavmK3YD3vgT3ZVdoiLrgBxClj1x0RvvAaiI2gl6FshysPPPve9+fiCMeYY2UhmLAAaZP0wzXuHjoXDUIRCjXTeXCauBOnpPwG9QWuK4zydpJTeE/KSfu16bGfPOyKbErJDYa/BgJjhUBGftTIcEQObib/32LJWkUFbwy3+U8PLbDnKYK2pJn9s1f6geklXif25lfAud3yYTssxaS4F2DY="

env:
  global:
    - PRODUCTION_BRANCH="production"
    # AWS_ACCESS_KEY_ID
    - secure: "u/3cyaOW8G4C3/oMSrWPNDEU6CcCmhPSweDwc1EEf/ch0jVC4LfQxtE9kLQRNO9uxCUOgZohMvBn+pArw7b6VPSjnMUhB6rldfjK7R2k+tLH/eSnkCQYaETLoZDqquJmzfrYcFd++pdSwZ8hFRgAOG7UkbII+cK88Q7ZYVeP6HwElLTm+zmyk7S56PQoohGVRgfJbSK34hLJfXMAG7n1nk+WckRX0CmmTMyZlrNOj6XeehXiZLhxY3/uKz0LvMv6ZLK3TgPtwz6jDrUi3uDn1Be6q4DrD3nkcmxjIRrmtvaxYYDw/Ulheg+eOuQwfMvr2RiUgeYOMDCqgqO2ljoMEvcZEBEc41WqHFakDHKWBOA4ideicVY1Y6QWpUah2p/ATPaPi3j0JkMtm3eer60+587viGfyomiH7YoeO5hUAXopipd0cmy+VzEzE7Jvw7vfes4isG+g7JWvKLh6L97tX9YhtmLcffqAmb8p7jJzn9kFMdRAYd+zsAgf0miQDUtDnhT/BTxHHafYvrTXOL+iAm9AVazyLr1XqsPtY2NxhhIK46ePEB6ivpqCaKnrVcvSVdxPTRvcQgnmz36MF4/OXLVz95x8kUOzrK0a8+OP8w7+M+iGcic0zZdMqG7iFKv6zRthx67wGgg71VzmPaqhHa6fxHAj6w7VEK68NJ/6fjg="
    # AWS_SECRET_ACCESS_KEY
    - secure: "RLHv4JHUu9dEtzH2vxTCaIZeFV0cGAxg559HxIO1IrdjDtnQD3h64u9PY0Ad5qRQaBoykuvXhy+3b9tDphX6OpWIWP7s30sniLOxpnRuAnoZHFTZ3KPjN5D9d37nwElGeydwtpoLePuhyuk6InatSG7I3rDAJNDbaLAUQLDtRERQslB9EKZNcGD9eAcjQYxf6LARfUjlYbBnBbGWMsGiOlKBRgGkDlRXqT0QEWK98oBiumPx6/uD3r4v7KL9BEXTudE581YdECfmH7nmcYo+PWWgzdGEHBvMc3deMdCYc4pHQOewEncBX2UStAIby6+t11q3FGgdedpsCTOli8R+O/lwcmWGNS6DXFwSwuV7aAeUKJMdFd4+of5kYSFdyzmW5alByEIWK5XlJwCFZUGnu5aSgYFLz/VXlA8a5oJbyChrZ+iuDaQvolaSr97OFGNX9IXrP2hN0M8Iee3O1EduOLw7bDJxX1B/NJfiQ5ipSJ0V4TeSo9DCpaKD6DZeVR7J5o144hygrnS8W8cEqSOUMjmRmXv9SISP17QMUEkNUreb6gAo3mm58rRzXStmvbj5cIalIsXyxpC/kvOZfhWgq1cSA22q3GQTtb2NEFx4OezgK6ic+qpY/LF3ci2F3aSlUiewRBluHDz8Fv5yzw1h82w2Rau0tfIivqU1geCSA/8="
    # DISTRIBUTION_ID
    - secure: "wTx+a/LIIw3ItZ51os70ICIbjNVf2eGD965IAHaBt6L5HPAeE9gnph+OU4wu5PSdga/HkM0MOwwm2wClr5K7qrEqbqy5d0WjOEPRlpcJ32jM9pTsCEf2rZIIO2U9MmFkBptChn+tdUCVirumPaSMBHG9ftQVeodGz2eQ6fsAIPKUrMfeakoTDrz9GeB29vlBzaDjh4lweqkgEcduEMNuQ9B65AhI/U3ytQbmom5kcT4sVwrd1gMnfVYLDwjkadiDciW6A7e9dz4rJ7Nr3VtxXVtEd9bypxAnARs/z3uza8s4FNZB6eosF2iVTYEXJne86hmi8gkyAZ5bCenSTkRpXmgVZB0GuHbvkJAwME1H3DEzLLfsodouCkEwo8GnfZ3OCr2zUzUR3+iyL84HUPmt0cEKZjYuNKih3fr3YfxJLCwohJU4n6ruKZMNsqnjPYyfbcl/tsV+DrG2BdbXWs+Z6oYs1TIb+3DQAfiQoCh2mYtRans1nENtfE6Y09rjIlAFUclM615NbRsxNUDUfuIQFvGA1V9KJ82qXNzaaTba+xwOVNHL+gKbcRcLPgIZ+WfQUH/nc/ed5YTkbh4RV2HedOM3aAq2g7leT6WPL4B5RQRYqXn65dnz2u0yAqBdpNyWRvfAMrPGhB4IsHWRYirUSnZdMBydZ2ci7VhzjEMZRMk="
