# docker-compose.yml for Skygear Getting Started Guide

# The volume container for database
# This container provides persistent storage for the `db` container. To
# remove this storage, run `docker-compose rm db_data`.
db_data:
  image: mdillon/postgis:9.4
  command: /bin/true

# The database container
db:
  image: mdillon/postgis:9.4
  volumes_from:
  - db_data
  ports:
  - "5432:5432"

# The volume container for skygear
# This container provides persistent storage for the `app` container. To
# remove this storage, run `docker-compose rm app_data`.
app_data:
  image: quay.io/skygeario/skygear-server:latest
  command: /bin/true

# The Skygear container
app:
  image: quay.io/skygeario/skygear-server:latest
  ports:
  - "3000:3000" # Skygear API Endpoint (HTTP)
  - "5555:5555" # Skygear Plugin Endpoint (ZMQ)
  volumes_from:
  - app_data
  links:
  - db
  command: skygear-server
  environment:
    # `db` in the following string should match the name of the database
    # container above.
    DATABASE_URL: postgresql://postgres:@db/postgres?sslmode=disable
    APP_NAME: myapp
    API_KEY: changeme
    MASTER_KEY: changeme
    # GOMAXPROCS - The maximum number of Go threads for execution.
    # When unspecified, the default is the number of CPU available, which
    # is the recommended setting.
    #GOMAXPROCS: 1
    # GODEBUG: netdns=cgo - Force go to use the cgo DNS resolver.
    # This is required because Docker container name is in /etc/hosts.
    GODEBUG: netdns=cgo
